import { LyricLine } from './types';

export const LYRICS: LyricLine[] = [
    { section: "Intro", text: "Navidades, Navidades", time: 10.0, imageKey: "navidad", visualDescription: "Christmas tree with lights night" },
    { section: "Intro", text: "Queremos polvorones, mazapanes y turrones", time: 12.0, imageKey: "turrones", visualDescription: "Christmas sweets turron marzipan chocolate" },
    { section: "Intro", text: "Por favore, Por favore", time: 16.2, imageKey: "navidad", visualDescription: "Santa Claus pleading funny" },
    { section: "Intro", text: "Felices vacacioneeeeeeeees", time: 19.3, imageKey: "vacaciones", visualDescription: "School closed for christmas snow" },
    { section: "Chorus", text: "Navidades, Navidades", time: 23.2, imageKey: "navidad", visualDescription: "Beautiful decorated Christmas tree" },
    { section: "Chorus", text: "Queremos polvorones, mazapanes y turrones", time: 26.1, imageKey: "turrones", visualDescription: "Pile of christmas candy and sweets" },
    { section: "Chorus", text: "Por favore, Por favore", time: 29.2, imageKey: "navidad", visualDescription: "Cute reindeer begging" },
    { section: "Chorus", text: "Los de sexto os deseamos", time: 32.7, imageKey: "colegio", visualDescription: "Happy school children waving" },
    { section: "Chorus", text: "Felices vacaciones", time: 35.7, imageKey: "vacaciones", visualDescription: "Beach with santa hat on sand" },
    { section: "Verse1", text: "Llegan las Navidades", time: 43.7, imageKey: "navidad", visualDescription: "Christmas lights bokeh city" },
    { section: "Verse1", text: "Con luces de colores", time: 45.4, imageKey: "luces", visualDescription: "Colorful christmas led lights close up" },
    { section: "Verse1", text: "Árbol y regalos son very importante", time: 47.6, imageKey: "arbol", visualDescription: "Huge pile of christmas gifts under tree" },
    { section: "Verse1", text: "No te olvides la carta", time: 50.9, imageKey: "carta", visualDescription: "Child writing letter to santa claus" },
    { section: "Verse1", text: "Que no te traen regalos", time: 53.3, imageKey: "regalos", visualDescription: "Empty christmas stocking sad" },
    { section: "Verse1", text: "Y de montar el belén en tu casa", time: 54.6, imageKey: "belen", visualDescription: "Nativity scene nativity set belen" },
    { section: "Verse1", text: "Monta bien la mesa", time: 57.6, imageKey: "cena", visualDescription: "Fancy christmas dinner table setting" },
    { section: "Verse1", text: "Que no quiero sorpresas", time: 59.1, imageKey: "cena", visualDescription: "Perfect cooked turkey christmas" },
    { section: "PreChorus", text: "No stresso, no stresso", time: 60.9, imageKey: "relax", visualDescription: "Relaxing by fireplace winter" },
    { section: "PreChorus", text: "No need to be depreso", time: 62.6, imageKey: "feliz", visualDescription: "Happy smiling snowman" },
    { section: "Chorus", text: "Navidades, Navidades", time: 65.0, imageKey: "navidad", visualDescription: "Golden christmas ornaments" },
    { section: "Chorus", text: "Queremos polvorones, mazapanes y turrones", time: 67.7, imageKey: "turrones", visualDescription: "Spanish polvorones and turron" },
    { section: "Chorus", text: "Por favore, Por favore", time: 71.1, imageKey: "navidad", visualDescription: "Elf asking please" },
    { section: "Chorus", text: "Felices vacacioneeeeeeeees", time: 74.9, imageKey: "vacaciones", visualDescription: "Snowy landscape winter wonderland" },
    { section: "Chorus", text: "Navidades, Navidades", time: 78.6, imageKey: "navidad", visualDescription: "Red christmas background decorations" },
    { section: "Chorus", text: "Queremos polvorones, mazapanes y turrones", time: 81.4, imageKey: "turrones", visualDescription: "Chocolate fountain sweets" },
    { section: "Chorus", text: "Por favore, Por favore", time: 84.7, imageKey: "navidad", visualDescription: "Christmas puppy with bow" },
    { section: "Chorus", text: "Los de sexto os deseamos", time: 88.4, imageKey: "colegio", visualDescription: "School children class photo christmas decorations" },
    { section: "Chorus", text: "Felices vacaciones", time: 91.2, imageKey: "vacaciones", visualDescription: "Tropical beach christmas palm tree" },
    { section: "Verse2", text: "Me voy de vacaciones", time: 94.4, imageKey: "vacaciones", visualDescription: "Car packed with luggage travel" },
    { section: "Verse2", text: "Con familia y amigos", time: 95.9, imageKey: "familia", visualDescription: "Big family christmas dinner happy" },
    { section: "Verse2", text: "Cantando villancicos, ganando aguinaldo", time: 97.4, imageKey: "villancicos", visualDescription: "Choir children singing carols snowy" },
    { section: "Verse2", text: "Estamos deseando", time: 100.4, imageKey: "feliz", visualDescription: "Excited child looking at tree" },
    { section: "Verse2", text: "Que lleguen vacaciones", time: 103.5, imageKey: "vacaciones", visualDescription: "Calendar marked december 25" },
    { section: "Verse2", text: "Pillar un pellizco de la lotería", time: 105.3, imageKey: "loteria", visualDescription: "Lottery balls lottery ticket celebration" },
    { section: "Verse2", text: "Toca la pandereta", time: 108.5, imageKey: "pandereta", visualDescription: "Playing tambourine christmas music" },
    { section: "Verse2", text: "No te quedes quieta", time: 110.5, imageKey: "baile", visualDescription: "Children dancing christmas school festival" },
    { section: "PreChorus", text: "No stresso, no stresso", time: 112.0, imageKey: "relax", visualDescription: "Sleeping cat under christmas tree" },
    { section: "PreChorus", text: "No need to be depreso", time: 113.9, imageKey: "feliz", visualDescription: "Fireworks happy celebration" },
    { section: "Chorus", text: "Navidades, Navidades", time: 115.9, imageKey: "navidad", visualDescription: "Sparklers christmas night" },
    { section: "Chorus", text: " Queremos polvorones, mazapanes y turrones", time: 118.3, imageKey: "turrones", visualDescription: "Tray of christmas cookies" },
    { section: "Chorus", text: "Por favore, Por favore", time: 121.4, imageKey: "navidad", visualDescription: "Three wise men camels silhouette" },
    { section: "Chorus", text: "Los de sexto os deseamos", time: 124.8, imageKey: "colegio", visualDescription: "Classroom chalkboard merry christmas" },
    { section: "Chorus", text: "Felices vacaciones", time: 127.7, imageKey: "vacaciones", visualDescription: "Sunset winter snow" },
    { section: "Outro", text: "Navidades, Navidades", time: 130.0, imageKey: "navidad", visualDescription: "Magical christmas forest glowing" },
    { section: "Outro", text: "FELIZ NAVIDAD", time: 141.1, imageKey: "final", visualDescription: "Fireworks text Merry Christmas 2026" },
];
