import { LyricLine } from './types';

export const LYRICS: LyricLine[] = [
    { section: "Intro", text: "Navidades, Navidades", time: 18.9, imageKey: "navidad", visualDescription: "Christmas tree with lights night" },
    { section: "Intro", text: "Queremos polvorones, mazapanes y turrones", time: 21.2, imageKey: "turrones", visualDescription: "Christmas sweets turron marzipan chocolate" },
    { section: "Intro", text: "Por favore, Por favore", time: 26, imageKey: "navidad", visualDescription: "Santa Claus pleading funny" },
    { section: "Intro", text: "Felices vacacioneeeeeeeees", time: 29.6, imageKey: "vacaciones", visualDescription: "School closed for christmas snow" },
    { section: "Chorus", text: "Navidades, Navidades", time: 34, imageKey: "navidad", visualDescription: "Beautiful decorated Christmas tree" },
    { section: "Chorus", text: "Queremos polvorones, mazapanes y turrones", time: 37.4, imageKey: "turrones", visualDescription: "Pile of christmas candy and sweets" },
    { section: "Chorus", text: "Por favore, Por favore", time: 40.9, imageKey: "navidad", visualDescription: "Cute reindeer begging" },
    { section: "Chorus", text: "Los de sexto os deseamos", time: 45, imageKey: "colegio", visualDescription: "Happy school children waving" },
    { section: "Chorus", text: "Felices vacaciones", time: 48.4, imageKey: "vacaciones", visualDescription: "Beach with santa hat on sand" },
    { section: "Verse1", text: "Llegan las Navidades", time: 57.6, imageKey: "navidad", visualDescription: "Christmas lights bokeh city" },
    { section: "Verse1", text: "Con luces de colores", time: 59.6, imageKey: "luces", visualDescription: "Colorful christmas led lights close up" },
    { section: "Verse1", text: "Árbol y regalos son very importante", time: 62.1, imageKey: "arbol", visualDescription: "Huge pile of christmas gifts under tree" },
    { section: "Verse1", text: "No te olvides la carta", time: 65.9, imageKey: "carta", visualDescription: "Child writing letter to santa claus" },
    { section: "Verse1", text: "Que no te traen regalos", time: 68.6, imageKey: "regalos", visualDescription: "Empty christmas stocking sad" },
    { section: "Verse1", text: "Y de montar el belén en tu casa", time: 70.1, imageKey: "belen", visualDescription: "Nativity scene nativity set belen" },
    { section: "Verse1", text: "Monta bien la mesa", time: 73.6, imageKey: "cena", visualDescription: "Fancy christmas dinner table setting" },
    { section: "Verse1", text: "Que no quiero sorpresas", time: 75.3, imageKey: "cena", visualDescription: "Perfect cooked turkey christmas" },
    { section: "PreChorus", text: "No stresso, no stresso", time: 77.4, imageKey: "relax", visualDescription: "Relaxing by fireplace winter" },
    { section: "PreChorus", text: "No need to be depreso", time: 79.3, imageKey: "feliz", visualDescription: "Happy smiling snowman" },
    { section: "Chorus", text: "Navidades, Navidades", time: 82.1, imageKey: "navidad", visualDescription: "Golden christmas ornaments" },
    { section: "Chorus", text: "Queremos polvorones, mazapanes y turrones", time: 85.2, imageKey: "turrones", visualDescription: "Spanish polvorones and turron" },
    { section: "Chorus", text: "Por favore, Por favore", time: 89.1, imageKey: "navidad", visualDescription: "Elf asking please" },
    { section: "Chorus", text: "Felices vacacioneeeeeeeees", time: 93.5, imageKey: "vacaciones", visualDescription: "Snowy landscape winter wonderland" },
    { section: "Chorus", text: "Navidades, Navidades", time: 97.7, imageKey: "navidad", visualDescription: "Red christmas background decorations" },
    { section: "Chorus", text: "Queremos polvorones, mazapanes y turrones", time: 101, imageKey: "turrones", visualDescription: "Chocolate fountain sweets" },
    { section: "Chorus", text: "Por favore, Por favore", time: 104.8, imageKey: "navidad", visualDescription: "Christmas puppy with bow" },
    { section: "Chorus", text: "Los de sexto os deseamos", time: 109, imageKey: "colegio", visualDescription: "Group of friends celebrating christmas" },
    { section: "Chorus", text: "Felices vacaciones", time: 112.2, imageKey: "vacaciones", visualDescription: "Tropical beach christmas palm tree" },
    { section: "Verse2", text: "Me voy de vacaciones", time: 115.9, imageKey: "vacaciones", visualDescription: "Car packed with luggage travel" },
    { section: "Verse2", text: "Con familia y amigos", time: 117.6, imageKey: "familia", visualDescription: "Big family christmas dinner happy" },
    { section: "Verse2", text: "Cantando villancicos, ganando aguinaldo", time: 119.4, imageKey: "villancicos", visualDescription: "Choir children singing carols snowy" },
    { section: "Verse2", text: "Estamos deseando", time: 122.8, imageKey: "feliz", visualDescription: "Excited child looking at tree" },
    { section: "Verse2", text: "Que lleguen vacaciones", time: 126.4, imageKey: "vacaciones", visualDescription: "Calendar marked december 25" },
    { section: "Verse2", text: "Pillar un pellizco de la lotería", time: 128.4, imageKey: "loteria", visualDescription: "Lottery balls lottery ticket celebration" },
    { section: "Verse2", text: "Toca la pandereta", time: 132.1, imageKey: "pandereta", visualDescription: "Playing tambourine christmas music" },
    { section: "Verse2", text: "No te quedes quieta", time: 134.4, imageKey: "baile", visualDescription: "People dancing at christmas party" },
    { section: "PreChorus", text: "No stresso, no stresso", time: 136.2, imageKey: "relax", visualDescription: "Sleeping cat under christmas tree" },
    { section: "PreChorus", text: "No need to be depreso", time: 138.3, imageKey: "feliz", visualDescription: "Fireworks happy celebration" },
    { section: "Chorus", text: "Navidades, Navidades", time: 140.7, imageKey: "navidad", visualDescription: "Sparklers christmas night" },
    { section: "Chorus", text: "Queremos polvorones, mazapanes y turrones", time: 143.4, imageKey: "turrones", visualDescription: "Tray of christmas cookies" },
    { section: "Chorus", text: "Por favore, Por favore", time: 147, imageKey: "navidad", visualDescription: "Three wise men camels silhouette" },
    { section: "Chorus", text: "Los de sexto os deseamos", time: 150.9, imageKey: "colegio", visualDescription: "Classroom chalkboard merry christmas" },
    { section: "Chorus", text: "Felices vacaciones", time: 154.2, imageKey: "vacaciones", visualDescription: "Sunset winter snow" },
    { section: "Outro", text: "Navidades, Navidades", time: 156.9, imageKey: "navidad", visualDescription: "Magical christmas forest glowing" },
    { section: "Outro", text: "FELIZ NAVIDAD", time: 169.6, imageKey: "final", visualDescription: "Fireworks text Happy New Year 2024" },
];